//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procheshta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int donorId { get; set; }
        public string donorName { get; set; }
        public int age { get; set; }
        public int weight { get; set; }
        public string gender { get; set; }
        public string bloodGroup { get; set; }
        public string contactNo { get; set; }
        public string email { get; set; }
        public string donorAddress { get; set; }
        public Nullable<System.DateTime> lastDonationDate { get; set; }
        public string donorImage { get; set; }
    }
}
